# Generated by Django 4.2.16 on 2024-12-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_zip_code_added_in_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unict_price',
        ),
    ]
