# Generated by Django 4.2.17 on 2025-01-08 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004__add_slug_to_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unict_price',
            new_name='unit_price',
        ),
    ]
